### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'novabot.geocoding' doesn't exist

### ISSUE THREAD

**Issue by PixelBurstHD** [novskey/novabot#21]
receiving the following after starting up - notifications appear to be working but this is spamming the logs

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'novabot.geocoding' doesn't exist
        at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
        at core.DBManager.setGeocodedLocation(DBManager.java:1353)
        at maps.ReverseGeocoder.geocodedLocation(ReverseGeocoder.java:87)
        at pokemon.PokeSpawn.<init>(PokeSpawn.java:77)
        at pokemon.PokeSpawn.<init>(PokeSpawn.java:141)
        at core.DBManager.getNewPokemon(DBManager.java:860)
        at notifier.PokeNotifier.run(PokeNotifier.java:27)
        at core.ScheduledExecutor$LogOnExceptionRunnable.run(ScheduledExecutor.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by novskey** [comment]
My bad, had the wrong DB script in the README. Use this one: https://github.com/novskey/novabot/blob/dev/create-db.sql

**Comment by PixelBurstHD** [comment]
<3 You and this bot are absolutely fantastic.

**Comment by novskey** [comment]
Thanks mate!
