### ISSUE TITLE
 [ ERROR] [PokeNotifier] An error ocurred in PokeNotifier

### ISSUE THREAD

**Issue by PixelBurstHD** [novskey/novabot#22]
[21:57:01] [ ERROR] [PokeNotifier] An error ocurred in PokeNotifier
java.lang.NullPointerException: null
        at core.Types.getEmote(Types.java:195)
        at pokemon.PokeSpawn.<init>(PokeSpawn.java:103)
        at pokemon.PokeSpawn.<init>(PokeSpawn.java:141)
        at core.DBManager.getNewPokemon(DBManager.java:860)
        at notifier.PokeNotifier.run(PokeNotifier.java:27)
        at core.ScheduledExecutor$LogOnExceptionRunnable.run(ScheduledExecutor.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Aby ideas on this one?

**Comment by PixelBurstHD** [comment]
I'm stupid suburbs.txt
