### ISSUE TITLE
issues with instalation

### ISSUE THREAD

**Issue by fallenflash** [novskey/novabot#3]
Throwing up these errors after following the guide 
windows 10, mariadb 10.2 java jre 8 64bit.  rocketmap

[20:19:45] [ INFO ] [novabot] Configuring...
[20:19:45] [ INFO ] [novabot] Loading config.ini...
Exception in thread "main" java.lang.NullPointerException
        at core.Config.<init>(Config.java:175)
        at core.NovaBot.loadConfig(NovaBot.java:65)
        at core.NovaBot.setup(NovaBot.java:754)
        at core.NovaBot.main(NovaBot.java:87)

**Comment by novskey** [comment]
Hey mate did you figure it out? Try the new release for me

**Comment by fallenflash** [comment]
new release seems to be working with just minor changes to config, once i get it all set up ill let u know how its going

**Comment by fallenflash** [comment]
so running into a couple other problems, while trying to setup and configure


####this occures directly following the raid query####
[06:50:34] [ INFO ] [DB] Query complete
[06:50:34] [ INFO ] [DB] Found: 0
[06:50:34] [ INFO ] [DB] Query complete
[06:50:34] [ ERROR] [RaidNotifier] An error ocurred in RaidNotifier
java.lang.NullPointerException: null
        at core.Team.getEmote(Team.java:57)
        at raids.RaidSpawn.<init>(RaidSpawn.java:65)
        at core.DBManager.getCurrentRaids(DBManager.java:642)
        at notifier.RaidNotifier.run(RaidNotifier.java:25)
        at core.ScheduledExecutor$LogOnExceptionRunnable.run(ScheduledExecutor.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[06:50:39] [ INFO ] [PokeNotifier] checking for pokemon to notify
[06:50:39] [ INFO ] [DB] Getting new pokemon
[06:50:39] [ INFO ] [DB] Executing query:com.mysql.jdbc.JDBC42PreparedStatement@54647d29: SELECT pokemon_id,       latitude,       longitude,       disappear_time,       individual_attack,        individual_defense,       individual_stamina,       move_1,       move_2,       weight,       height,       gender,       form,       cp,        cp_multiplier FROM pokemon WHERE pokemon_id NOT IN ('21','23','29','32','41','48','60','98','115','118','120','183','161','165','167','177','194','198') AND last_modified >= DATE_SUB('2017-12-22 11:50:34',INTERVAL 1 SECOND)
[06:50:39] [ INFO ] [DB] Query complete
[06:50:39] [ INFO ] [DB] Found: 0

####and this is after me adding, seedot, delibird, pidgey, eevee and more with 0 notifications###

**Comment by novskey** [comment]
Do you have the new icons folder with the team icons?

**Comment by fallenflash** [comment]
yessir

**Comment by fallenflash** [comment]
i downloaded your newer release

**Comment by fallenflash** [comment]
I can provide full logs if it would help

**Comment by novskey** [comment]
Yes please. And you have static/icons/Valor.png etc?

**Comment by fallenflash** [comment]
ok so i figured out why it was loading, [sorry]
![capture](https://user-images.githubusercontent.com/29239060/34456535-e64bb526-ed66-11e7-95b1-cf3dd0b4d6f3.PNG)
 for the slow response been busy with the holidays, but it was an issue with my google maps key, but still not getting notifications for pokemon, just raids now.
thats my config, im gonna keep looking at it to see its something stupid again ive missed

**Comment by novskey** [comment]
Are Pokémon being found in the process log?

**Comment by fallenflash** [comment]
so earlier today before discord went on the fritz, it popped a couple of delibird (changed the filter to delibird and gulpin since theres a bajillion for testing)  but i started it back up and its back to finding none

**Comment by fallenflash** [comment]
AHHHHHHH!!!!! i take that back
it just took some time...  thy all came in at once..  142 notifications on discord

**Comment by novskey** [comment]
Have any spawned? Are u in the discord server ? Easier to chat there

**Comment by fallenflash** [comment]
i am not, but whats the link i was looking for one everywhere cuz that would be so much easier

**Comment by novskey** [comment]
https://discord.gg/P3qrvkp
